name: Publish

on:
  push:
    branches:
      - master
      - third-party-action

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Output Bikeshed to HTML
        uses: netwerk-digitaal-erfgoed/bikeshed-action@v1

      - uses: w3c/spec-prod@v2
      - uses: actions/configure-pages@v3

      - uses: actions/upload-pages-artifact@v1
        with:
          path: '.'

      - id: deployment
        uses: actions/deploy-pages@v2
